import { GitBranch } from "lucide-react";
import { C, MONO, DISPLAY } from "../config.js";
import { Glass, Label, Legend } from "./ui.jsx";

export default function TaskGraph({ tasks }) {
  const W = 640, H = 300, cx = W / 2;
  const shown = (tasks || []).slice(0, 8);
  const per = shown.length || 1;
  const nodes = shown.map((t, i) => ({
    ...t,
    x: per === 1 ? cx : 60 + (i / Math.max(1, per - 1)) * (W - 120),
    y: t.source === "loop" ? 250 : 150,
  }));
  const col = (t) =>
    t.status === "done" ? C.green : t.status === "rejected" ? C.red : t.needsApproval ? C.amber : C.cyan;

  return (
    <Glass style={{ padding: 16 }}>
      <Label icon={GitBranch}>AUTONOMOUS TASK GRAPH</Label>
      <div style={{ overflowX: "auto", marginTop: 10 }}>
        <svg viewBox={`0 0 ${W} ${H}`} style={{ width: "100%", minWidth: 520, height: 300 }}>
          <circle cx={cx} cy={50} r={26} fill="#11162a" stroke={C.violet} strokeWidth="2" />
          <text x={cx} y={54} textAnchor="middle" fontSize="11" fill="#fff" fontFamily={MONO}>CORE</text>
          {nodes.map((n) => (
            <line key={"l" + n.id} x1={cx} y1={76} x2={n.x} y2={n.y - 18}
              stroke={col(n) + "66"} strokeWidth="1.5" strokeDasharray={n.source === "loop" ? "4 4" : "0"} />
          ))}
          {nodes.map((n) => (
            <g key={n.id}>
              <circle cx={n.x} cy={n.y} r={18} fill="#0d1124" stroke={col(n)} strokeWidth="2" />
              <text x={n.x} y={n.y + 4} textAnchor="middle" fontSize="9" fill={col(n)} fontFamily={MONO}>
                {String(n.owner || "").slice(0, 4)}
              </text>
              <text x={n.x} y={n.y + 36} textAnchor="middle" fontSize="9" fill="#9aa3c8" fontFamily={MONO}>
                {n.title.length > 22 ? n.title.slice(0, 21) + "…" : n.title}
              </text>
              {n.needsApproval && <circle cx={n.x + 14} cy={n.y - 14} r={4} fill={C.amber} />}
            </g>
          ))}
        </svg>
      </div>
      <div style={{ display: "flex", gap: 14, marginTop: 8, flexWrap: "wrap", fontSize: 10, color: C.dim, fontFamily: DISPLAY }}>
        <Legend c={C.cyan}>approved</Legend>
        <Legend c={C.amber}>gated</Legend>
        <Legend c={C.green}>done</Legend>
        <Legend c={C.red}>rejected</Legend>
        <span style={{ marginLeft: "auto" }}>dashed = generated by improvement loop</span>
      </div>
      {(tasks || []).length > 8 && (
        <div style={{ fontSize: 10, color: C.dim, marginTop: 6 }}>+{tasks.length - 8} more in queue</div>
      )}
    </Glass>
  );
}
